<a href="https://colab.research.google.com/github/karinasaidene/DS_bootcamp_homework/blob/main/computation_graphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import timeit

In [4]:
def eager_sigmoid_function(x) :
  return 1/(1+tf.math.exp(-x))

x = tf.random.uniform([10])
eager_sigmoid_function(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.51640064, 0.6364688 , 0.5316525 , 0.56824785, 0.72306716,
       0.57698786, 0.66488844, 0.57708776, 0.58303547, 0.5355431 ],
      dtype=float32)>

In [6]:
graph_sigmoid_function = tf.function (eager_sigmoid_function)
graph_sigmoid_function(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.51640064, 0.6364688 , 0.5316525 , 0.56824785, 0.72306716,
       0.57698786, 0.66488844, 0.57708776, 0.58303547, 0.5355431 ],
      dtype=float32)>

In [7]:
print("eager_time :",timeit.timeit(lambda:eager_sigmoid_function(x) , number = 100 ))
print("graph_time :",timeit.timeit(lambda:graph_sigmoid_function(x) , number = 100 ))

eager_time : 0.02091126700008772
graph_time : 0.03686024900002849
