In [1]:
from sklearn.datasets import load_iris
iris= load_iris()

In [21]:
# Store features matrix in X
dat= iris.data
#Store target vector in 
tar= iris.target


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [3]:
#convert it into a dataframe
import pandas as pd
import numpy as np
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                  columns= iris['feature_names'] + ['Species'])

In [4]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Species  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
..       ...  
145      2.0  
146      2.0  
147      2.0  
148      2.0  
149      2.0  

[150 rows x 5 columns]

## 1-question 1


In [12]:
from sklearn.model_selection import train_test_split
x=df.iloc[:,:-1].values
y=df.iloc[:,-1:].values
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
from sklearn.linear_model import LogisticRegression
sk_model=LogisticRegression()

In [14]:
sk_model.fit(x_train, y_train)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
#define the get_accuracy function
def get_accuracy(y_predict,y_test):
    correctly_classified=0
    for count in range(np.size(y_predict)):
        if y_test[count]==y_predict[count]:
            correctly_classified=correctly_classified+1
    acc=(correctly_classified/len(y_predict))*100
    print("accuracy on testset={:.2f}".format(acc))
    return acc
 

In [16]:
y_predict=sk_model.predict(x_test)


In [17]:
accur=get_accuracy(y_predict,y_test)

accuracy on testset=100.00


# 2-question 2
Here I will be using confusion Matrix 


In [27]:
from sklearn.metrics import classification_report, confusion_matrix
class_names = iris.target_names
print(classification_report(y_test, y_predict, target_names=class_names))
print(confusion_matrix(y_test, y_predict))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


# interpret results 

The model is correctly predcting the positive class

-we correctly predicted that 11 of them belong to setosa spicies

-we correctly predicted that 13 of them belong to versicolor spicies

-we correctly predicted that 6 of them belong to virginica spicies

the Recall is equal to 1.00 so we can say that when the actual value is positive the prediction is correct


The precision is equal to 1.00 so we can say that the classifier is well precise when predicting positive values 